### PR TITLE
Force locale python3

### PR DESCRIPTION
**Pull request by adarshk7**

### CODE REVIEW

**Comment by lalinsky** [comment]
It seems that you rebased my commits somehow. I'll just cherry-pick your commit. I realized I never opened a pull request to mitsuhiko's repo. I'll do that after I merge your change.

**Comment by adarshk7** [comment]
I rebased `force-locale` to my branch, but I am not sure why it shows your commits because I am trying to merge this to the same branch. But thanks! :D PR to mitsuhiko's repo would be awesome.

**Comment by lalinsky** [comment]
If you rebase a branch, you essentially create a new commit for every commit since the "base" you are rebasing against.

Anyway, I have cherry-picked the commit in 37a2a802f1a2585c. GitHub will not recognize that as a merge, so I'll close this.

**Comment by adarshk7** [comment]
Didn't know that, thanks!

**Comment by lalinsky** [comment]
https://github.com/mitsuhiko/flask-babel/pull/72

**Pull request closed without merging**
